FROM centos:7
LABEL maintainer="Andrei Andryieuski" \
      version="1.0"

WORKDIR /tmp
RUN yum -y update
RUN yum -y install httpd php gcc glibc glibc-common wget gd gd-devel perl postfix make gettext automake autoconf openssl-devel net-snmp net-snmp-utils epel-release perl-Net-SNMP which unzip

RUN useradd nagios && \
    echo "nagios" | passwd nagios --stdin && \
    groupadd nagioscmd && \
    usermod -G nagioscmd nagios && \
    usermod -G nagioscmd apache

RUN wget -q https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.2.tar.gz -O nagioscore.tar.gz && \
    tar xzf nagioscore.tar.gz && \
    cd /tmp/nagioscore-nagios-4.4.2 && \
    ./configure --with-comand-group=nagioscmd && \
    make all && \
    make install-groups-users && \
    usermod -a -G nagios apache && \
    make install && \
    make install-init && \
    make install-config && \
    make install-commandmode && \
    make install-webconf 

RUN echo "nagiosadmin" | htpasswd -cb /usr/local/nagios/etc/htpasswd.users nagiosadmin --stdin

RUN cd /tmp && \
    wget --no-check-certificate -O nagios-plugins.tar.gz https://github.com/nagios-plugins/nagios-plugins/archive/release-2.2.1.tar.gz && \
    tar zxf nagios-plugins.tar.gz && \
    cd /tmp/nagios-plugins-release-2.2.1/ && \
    ./tools/setup && \
    ./configure  && \
    make && \
    make install 


RUN usermod -G apache nagios


COPY nagios-entrypoint.sh /tmp/
RUN chown nagios:nagios /tmp/nagios-entrypoint.sh && \
    chmod +x /tmp/nagios-entrypoint.sh

USER nagios

EXPOSE 80

ENTRYPOINT ["/tmp/nagios-entrypoint.sh"]
CMD ["/usr/local/nagios/bin/nagios","/usr/local/nagios/etc/nagios.cfg"]
